# PremiumLogin 1.0 by NotReference
# AutoLogin Premium Players Easily. AuthMeBungee Support. Require AuthMe with BungeeCord Hook enabled to Work.

# - Utils -

# Select the authentication server.
auth-server: Auth

# Minecraft in the 1.6 implemented a new Authentication service. If you type this true, players with 1.5 ecc.. can login with premium too..
allow-premium-legacy-connections: false

# List of players with premium auto login enabled.
# Moved on players.yml

# If a registered premium player, not join with the official premium minecraft launcher, will be kicked.
# Obligatory or plugin will not work.

# Log all actions to online staffs with permission premiumlogin.staff
log-staff: true

# Allow to use PremiumLogin if the server is online mode. [BETA] This can be bugged. I recommend you to put this false.
allow-online: false 

# Permission for do /premium. Type nessuno for no permission.
premium-permission: nessuno

# - Messages -


join-with-premium: '&cYou are not authenticated through Minecraft.net'
auto-login-premium: '&aPremium account found. You have been forcelogged.'
error-generic: '&cAn error has occurred.'
default-login-system-switch-to-premiumlogin: '&aYour default login system has been switched to PremiumLogin.'
default-login-system-switch-to-authme: '&aYour default login system has been switched to AuthMe.'
enabled-autologin: '&aYou can now autologin with premium account.'
disable-autologin: '&eYou disabled autologin with premium account.'
no-premium: '&cYou are not premium.'
no-legacy: '&cSorry, currently we do not support legacy premium connections. Login with 1.7+'
not-used-premium-launcher: '&cFor enable this function, you need to be logged from the official &cMinecraft Premium Launcher.'
no-perms: '&cYou do not have permissions.'


# - Log Messages -
#[utente] for user name.
#[uuid] for uuid.
#[ip] for IP.

user-forcelogged: '&b[utente] &7has been forcelogged because is &aPremium&7.'
try-join-nopremium: '&b[utente] &7tried to join without the &eOfficial Minecraft Launcher&7.'
